### ISSUE TITLE
💥 Stop making breaking changes

### ISSUE THREAD

**Issue by amcdnl** [okta/okta-react#118]
Dear Okta Developers and PMs:

This library along with the  `@okta/okta-signin-widget` and `@okta/okta-auth-js` have been version revving and introducing breaking changes ( for little to no reason ). As a developer, I expect libraries coming from a commercial product to be fairly stable and work together with their other libraries very nicely. At this point, I can't trust this library or the other libraries I have mentioned to work together at all without several iterations of add/remove/revert and this has forced me to lock my versions and not upgrade. I urge you to introduce a beta channel, make sure all the libraries work together before releasing and show a little empathy for the developers using this library.

Sincerely - 

Ordinary developer who wants a easy upgrade path

**Comment by ryanmr** [comment]
I have run into this as well. There's not much indication that @okta/okta-auth-js and @okta/okta-react are somewhat incompatible at this time.

**Comment by tbarrettwilsdon** [comment]
Couldn't agree more - it's currently in an unusable state for a developer starting a new project, which I discovered when attempting to deploy a new app based on 5.x for `okta-react` and `okta-auth-js` - all the readme documentation is completely wrong now and pieces of okta-react are inherently incompatible with okta-auth-js 5.x despite requiring it!

**Comment by mraible** [comment]
I hear what y'all are saying. I stumbled upon this issue myself when upgrading to Auth JS 5.0 this morning. It took me a while (and some internal help) to realize that v5.1.1 depends on Auth JS 4.8.0. 

https://github.com/okta/okta-react/blob/master/package.json#L43

I did test Okta React 5.1.1 with Auth JS 4.9.0 and proved it works. In case you aren't aware, the [Okta CLI](https://cli.okta.com) provides an easy way to create a React app with the proper dependencies.

```
okta start react
```

This pulls from https://github.com/okta-samples/okta-react-sample. I try to update this repo weekly.

**Comment by tbarrettwilsdon** [comment]
> I hear what y'all are saying. I stumbled upon this issue myself when upgrading to Auth JS 5.0 this morning. It took me a while (and some internal help) to realize that v5.1.1 depends on Auth JS 4.8.0.
> 
> https://github.com/okta/okta-react/blob/master/package.json#L43
> 
> I did test Okta React 5.1.1 with Auth JS 4.9.0 and proved it works. In case you aren't aware, the [Okta CLI](https://cli.okta.com) provides an easy way to create a React app with the proper dependencies.
> 
> ```
> okta start react
> ```
> 
> This pulls from https://github.com/okta-samples/okta-react-sample. I try to update this repo weekly.

Appreciate the update! I think the bulk of the confusion likely stems from the fact that all documentation has you install `npm install --save @okta/okta-auth-js` without a pinned version separately, which grabs the latest version (and is inherently incompatible with the latest version of okta-react) so anyone who is following any of [Okta's quickstart guide](https://developer.okta.com/code/react/okta_react_sign-in_widget/#install-dependencies) or even just this repo's README is going to find themselves in a very confusing situation.

**Comment by aarongranick-okta** [comment]
@tbarrettwilsdon Thank you for the information. `okta-react` is "downstream" from `okta-auth-js` so whenever a new version of `okta-auth-js` is released there is a moment in time before the downstream SDKs are updated. A version of `okta-react` that is compatible with `okta-auth-js` version 5 will be coming soon (internal ref: OKTA-392445) We will also update documentation in the README and quickstart guide.

**Comment by kellengreen** [comment]
Suddenly making `restoreOriginalUri` prop required is a great example of this. Why not make it optional and have it behave as it did prior?

This could even have been temporarily with a depreciation notice: "this prop will soon be required".  This will at least give developers a heads up to the impending change.

**Comment by amcdnl** [comment]
> Suddenly making the`restoreOriginalUri` prop required is a great example of this. Why not make it optional and have it behave as it did prior?
> 
> It even could have been temporarily by serving a depreciation notice: "this prop will soon be required". This way developers would at least be given a heads up to the impending change.

+1000 to this!

**Comment by amcdnl** [comment]
> @tbarrettwilsdon Thank you for the information. `okta-react` is "downstream" from `okta-auth-js` so whenever a new version of `okta-auth-js` is released there is a moment in time before the downstream SDKs are updated. A version of `okta-react` that is compatible with `okta-auth-js` version 5 will be coming soon (internal ref: OKTA-392445) We will also update documentation in the README and quickstart guide.

I understand the dependencies here but it should have never been released until all components are compatible ( or at minimal some sort of error/warning/notification ). This is a commercial product ( despite it being on Github - you prove that by referencing internal tickets and not even merging my pull requests in the past ) - we as developers have to use this thing day in and day out and having bosses asking us why is this not working, we paid $$ for Okta.

**Comment by shuowu** [comment]
> one suggestion is to lock the okta-auth-js module with caret (^) to make sure that both major versions are compatible. Then upgrade both packages together when needed.

Shared from another issue https://github.com/okta/okta-react/issues/119#issuecomment-831914696

We'll also look into patterns to prevent this kind of accidental breaking change (upstream change breaks the downstream without intentionally upgrade) to make the SDK robust.

**Comment by ArtyEmsee** [comment]
> I hear what y'all are saying. I stumbled upon this issue myself when upgrading to Auth JS 5.0 this morning. It took me a while (and some internal help) to realize that v5.1.1 depends on Auth JS 4.8.0.
> 
> https://github.com/okta/okta-react/blob/master/package.json#L43
> 
> I did test Okta React 5.1.1 with Auth JS 4.9.0 and proved it works. In case you aren't aware, the [Okta CLI](https://cli.okta.com) provides an easy way to create a React app with the proper dependencies.
> 
> ```
> okta start react
> ```
> 
> This pulls from https://github.com/okta-samples/okta-react-sample. I try to update this repo weekly.

I just upgraded to react-okta 5.1.1 and my experience was that it did _not_ work with okta-auth-js, I was seeing a typescript error on the `oktaAuth` object-- but it did work 4.9.0.

**Comment by khitrenovich** [comment]
> I hear what y'all are saying. I stumbled upon this issue myself when upgrading to Auth JS 5.0 this morning. It took me a while (and some internal help) to realize that v5.1.1 depends on Auth JS 4.8.0.

Not only _depends_ - it is practically pinned there, and you can't really upgrade because you end up with 2 copies of Auth JS in you bundle (see https://github.com/okta/okta-react/issues/114).

**Comment by cmacdonnacha** [comment]
I just did `npm install @okta/okta-auth-js @okta/okta-react` which installed 

```
"@okta/okta-auth-js": "^5.0.1",
"@okta/okta-react": "^5.1.2",
```

After setting up the config I'm getting this error:

`AuthSdkError: Passed in oktaAuth is not compatible with the SDK, okta-auth-js version 4.x is the current supported version.`

From reading above it sounds like there's some mismatch. Anyone know which versions of both work best together?

**Comment by cmacdonnacha** [comment]
> Suddenly making the `restoreOriginalUri` prop required is a great example of this. Why not make it optional and simply behave as it did prior?
> 
> It even could have been temporarily by serving a depreciation notice: `prop will soon be required`. This way developers would at least be given a heads up to the impending change.

Would be great to update the docs to add in this new required prop as well: https://developer.okta.com/docs/guides/sign-into-spa/react/configure-the-sdk/

**Comment by khitrenovich** [comment]
> Anyone know which versions of both work best together?

@cmacdonnacha From my experience - pick latest `okta-react` (v5.1.2) and `okta-auth-js` v4.8 (due to #114).

**Comment by cmacdonnacha** [comment]
> > Anyone know which versions of both work best together?
> 
> @cmacdonnacha From my experience - pick latest `okta-react` (v5.1.2) and `okta-auth-js` v4.8 (due to #114).

Thank @khitrenovich, I'm going to lock `package.json` to use these two for now.

**Comment by denysoblohin-okta** [comment]
okta-react 6 will be released soon and will support okta-auth-js 5

**Comment by shuowu** [comment]
@cmacdonnacha With okta-react v5.1.2, it throws a runtime error if there is a mismatch in versions. See details [here](https://github.com/okta/okta-react/pull/123).

**Comment by chinanderm** [comment]
What a mess! 🥴

**Comment by DanielJoyce** [comment]
Ok, wow, okta needs to do a better job of version pinning it seems.

**Comment by DanielJoyce** [comment]
Trying to use okta-auth-js 5 with okta-react 6

Trying to use the <Security> component results in

```
Property 'restoreOriginalUri' is missing in type '{ children: Element; oktaAuth: OktaAuthBrowser; }' but required in type '{ oktaAuth: OktaAuthBrowser; restoreOriginalUri: RestoreOriginalUriFunction; onAuthRequired?: OnAuthRequiredFunction | undefined; children?: ReactNode; }'.  
```

Super frustrating

**Comment by mraible** [comment]
@DanielJoyce I upgraded one of our samples yesterday to use Okta React v6 and Auth JS v5. Maybe it'll help? https://github.com/okta-samples/okta-react-sample/commit/3e8e7cf4e2ace25de2880685ba85360ea79fdba8

You could also test it out with the [Okta CLI](https://cli.okta.com). Just run `okta start react`. Here's [a video](https://youtu.be/V3G8-nfWQoM) that shows how it works.

**Comment by DanielJoyce** [comment]
The problem is the typescript definitions are booked which breaks compilation for me.

**Comment by cmacdonnacha** [comment]
Will okta-react v6 work ok with [okta-auth-js v5.2](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-5.2.0) that was released 3 days ago?

**Comment by oleksandrpravosudko-okta** [comment]
@cmacdonnacha okta-auth-js@5.2.0 is expected to work fine with okta-react v6 (there seem to be no known issues; I also tried 5.2.0 in custom-login sample app with no errors spotted).

@DanielJoyce TS definitions are [emitted](https://github.com/okta/okta-react/blob/master/tsconfig.json#L3) and packaged during library build - they should be in sync with package's code. Can you please share code which throws compilation errors?

**Comment by DanielJoyce** [comment]
They should be, but this ticket implies otherwise:

https://github.com/okta/okta-react/issues/140  Authstate can be null though types implies otherwise

https://github.com/okta/okta-react/issues/119  

<Security> component complains with:

```
Property 'restoreOriginalUri' is missing in type '{ children: Element; oktaAuth: OktaAuthBrowser; }' but required in type '{ oktaAuth: OktaAuthBrowser; restoreOriginalUri: RestoreOriginalUriFunction; onAuthRequired?: OnAuthRequiredFunction | undefined; children?: ReactNode; }'.  
```

**Comment by DanielJoyce** [comment]
Looking at tsconfig json

```
    "noImplicitAny": false,
```

**Comment by DanielJoyce** [comment]
```
app/App.tsx(85,12):
Property 'restoreOriginalUri' is missing in type '{ children: Element; oktaAuth: OktaAuth; }' but required in type '{ oktaAuth: OktaAuth; restoreOriginalUri: RestoreOriginalUriFunction; onAuthRequired?: OnAuthRequiredFunction | undefined; children?: ReactNode; }'.  TS2741

    83 |       <Router>
    84 |         <Contexts>
  > 85 |           <Security oktaAuth={oktaAuth}>
       |            ^
    86 |             <Switch>
    87 |               <Route path={ROUTES.LOGIN.path} component={AuthView} />
    88 |               <Route path={ROUTES.INDEX.path} component={AppContent} />
```

**Comment by MassivDash** [comment]
I hope Okta team will use this more as a feedback thread than just simple lashing out. I am joined in pain with most developers here. 

For me the crucial thing is documenting why new breaking changes are being implemented, Is it because it implements additional security ? Is it because the new version is faster ? 

Are there any dangers to using okta 5 or 4 in compre to new version 6 ? 
What are the benefits of moving to a new version. 

If you look at the release schedule, each major break occurred in 3/4 months period. IMO this a bit extreme, unless it's required because of sec reasons, documenting why those changes were implemented should ease off some of the frustrations that people post here.

- Document why major changes are being implemented 
- If old methods are secure, leave them with deprecating warnings for at least one major bump
- Create a roadmap for future changes, so devs know what to expect in the future 
- The readme doc because of this breaking changes are getting longer and longer, maybe you should separate them into different files.
- Please try to understand that most devs do not have the time to reimplement the authentication method every 3 months (unless required by security issues). 

At this moment I am forced to use Okta because it's required by my corp, however because of the dev experience I would not recommend Okta to any developer or organisation.

**Comment by DanielJoyce** [comment]
Docs need to be kept up to date with releases too. I've definitely run into bugs in docs vs what  typescript says.

**Comment by DanielJoyce** [comment]
Setting `strict: true` in tsconfig.json points out several areas where authstate being null might not be properly handled.

**Comment by DanielRuf** [comment]
Does anyone have an example for implicit callback and the exact version numbers which work in combination?

After an upgrade to okta-react v6 and okta-auth-js v5 (both latest releases) `authState` is null for me.
